---
# tasks file for arillso.apt

- name: 'install apt-transport-https'
  apt:
    name: apt-transport-https
    state: present

- name: 'install unattended-upgrades'
  apt:
    pkg: 'unattended-upgrades'
    state: "{{ 'latest' if apt_unattended_upgrades else 'absent' }}"

- name: 'include templates generate'
  include_tasks: templates.yml
  with_items:
    - name: 'General'
      value: '10'
    - name: 'Periodic'
      value: '10'
    - name: 'Archives'
      value: '10'
  loop_control:
    loop_var: apt_loop_template

- name: 'include templates generate'
  include_tasks: templates.yml
  when: apt_loop_template.when is defined and apt_loop_template.when
  with_items:
    - name: 'Unattended-upgrades'
      value: '50'
      when: '{{ apt_unattended_upgrades }}'
  loop_control:
    loop_var: apt_loop_template
